# Generated by Django 5.2.15 on 2026-06-06 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('name', models.CharField(max_length=50, verbose_name='Kategoriya nomi')),
                ('callback_data', models.CharField(max_length=50, unique=True, verbose_name='Tugma (Callback) data')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivmi?')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': '2. Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': '1. Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('details', models.JSONField(default=dict, verbose_name="E'lon tafsilotlari")),
                ('phone_numbers', models.CharField(max_length=255, verbose_name='Aloqa raqamlari')),
                ('status', models.CharField(choices=[('draft', 'Qoralama (Yozilmoqda)'), ('pending', 'Kutilmoqda (Adminga yuborilgan)'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='draft', max_length=20, verbose_name='Holati')),
                ('message_ids', models.JSONField(blank=True, default=list, verbose_name='Xabar ID lari')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.category', verbose_name='Kategoriya')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "3. Barcha E'lonlar",
            },
        ),
    ]
