# Generated by Django 5.2.15 on 2026-06-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(max_length=255, verbose_name='Lavozim / Kasb')),
                ('company', models.CharField(max_length=255, verbose_name='Ish joyi nomi')),
                ('salary', models.CharField(max_length=100, verbose_name='Maosh (Oylik)')),
                ('requirements', models.TextField(verbose_name='Talablar va Sharoitlar')),
                ('phone', models.CharField(max_length=100, verbose_name='Aloqa uchun raqam')),
                ('is_active', models.BooleanField(default=True, verbose_name="Aktivmi? (Saytda ko'rinishi)")),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': '4. Vakansiyalar',
            },
        ),
    ]
